# Generated by Django 3.2.7 on 2023-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('conclusion_investigacion', models.TextField()),
                ('conclusion_desarrollo', models.TextField()),
                ('conclusion_integracion', models.TextField()),
                ('conclusion_propiedad', models.TextField()),
                ('conclusion_normatividad', models.TextField()),
                ('conclusion_manufactura', models.TextField()),
                ('conclusion_usuarios', models.TextField()),
                ('conclusion_aspectos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('estatus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('promedio_trl1', models.FloatField(max_length=5)),
                ('promedio_trl2', models.FloatField(max_length=5)),
                ('promedio_trl3', models.FloatField(max_length=5)),
                ('promedio_trl4', models.FloatField(max_length=5)),
                ('promedio_trl5', models.FloatField(max_length=5)),
                ('promedio_trl6', models.FloatField(max_length=5)),
                ('promedio_trl7', models.FloatField(max_length=5)),
                ('promedio_trl8', models.FloatField(max_length=5)),
                ('promedio_trl9', models.FloatField(max_length=5)),
                ('promedio_trl_global', models.FloatField(max_length=5)),
                ('promedio_investigacion', models.FloatField(max_length=5)),
                ('promedio_desarrollo', models.FloatField(max_length=5)),
                ('promedio_integracion', models.FloatField(max_length=5)),
                ('promedio_propiedad', models.FloatField(max_length=5)),
                ('promedio_normatividad', models.FloatField(max_length=5)),
                ('promedio_manufactura', models.FloatField(max_length=5)),
                ('promedio_usuarios', models.FloatField(max_length=5)),
                ('promedio_aspectos', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('recomendacion_investigacion', models.TextField()),
                ('recomendacion_desarrollo', models.TextField()),
                ('recomendacion_integracion', models.TextField()),
                ('recomendacion_propiedad', models.TextField()),
                ('recomendacion_normatividad', models.TextField()),
                ('recomendacion_manufactura', models.TextField()),
                ('recomendacion_usuarios', models.TextField()),
                ('recomendacion_aspectos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_proyecto', models.CharField(max_length=500)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('categoria', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pregunta', models.FloatField(max_length=3)),
                ('categoria_pregunta', models.CharField(max_length=70)),
                ('respuesta', models.CharField(max_length=10)),
            ],
        ),
    ]
