# Generated by Django 3.2.7 on 2023-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='nombre_proyecto',
            field=models.CharField(default='', max_length=500),
        ),
    ]
