# Generated by Django 3.2.7 on 2023-03-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0004_auto_20230315_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta1_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta1_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2_5',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta2_6',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3_5',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta3_6',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_5',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_6',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_7',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta4_8',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta5_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta5_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta5_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta5_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta6_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta6_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta6_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta6_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta6_5',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta7_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta7_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta7_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta7_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta8_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta8_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta8_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta8_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta8_5',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta9_1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta9_2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta9_3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pregunta9_4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl1',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl2',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl3',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl4',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl5',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl6',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl7',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl8',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='promedio_trl9',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
