# Generated by Django 3.2.7 on 2023-03-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0005_auto_20230315_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
