# Generated by Django 3.2.7 on 2023-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0010_auto_20230426_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='pregunta6_0',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
