# Generated by Django 3.2.7 on 2023-05-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0013_auto_20230525_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='romendacion_pregunta1_1',
            new_name='recomendacion_pregunta1_1',
        ),
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='romendacion_pregunta1_2',
            new_name='recomendacion_pregunta1_2',
        ),
    ]
