# Generated by Django 3.2.7 on 2023-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='numero_res',
            field=models.IntegerField(),
        ),
    ]
